name: GitHub Actions Workflow Hub | Producer Workflow

on:
  workflow_dispatch:
    inputs:
      user_input:
          description: 'Your input goes here'
          required: true

jobs:
  producer_job:
    name: Producer Job
    uses: jacekmaciag/github_actions_workflow_hub/.github/workflows/hub.yml@master
    secrets: inherit
    with:
      user_input: ${{ inputs.user_input }}
      # ... other inputs
